version: '3'
services:
    web:
      image: nginx:latest
      container_name: nginx2container
      ports:
        - "8080:80"
      volumes:
        - ./code:/code
        - ./nginx.conf:/etc/nginx/conf.d/default.conf
      links:
        - php
        - mysql

    php:
      build:
        context: .
      container_name: phpcontainer
      volumes: 
        - ./code:/code
      links:
        - mysql

    mysql:
      image: mysql:5.7.22
      container_name: mysqlcontainer
      ports:
        - "3306:3306"
      environment:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      volumes:
        - ./data/db/mysql:/var/lib/mysql
        - ./code:/code
