version: '3'
services:
    web:
      image: nginx:latest
      container_name: nginx2
      ports:
        - "8080:80"
      volumes:
        - ./code:/code
        - ./nginx.conf:/etc/nginx/conf.d/default.conf
      links:
        - php
        - mysql

    php:
      image: php:7-fpm
      volumes: 
        - ./code:/code
      links:
        - mysql

    mysql:
      image: mysql:latest
      ports:
        - "3306:3306"
      environment:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      volumes:
        - "./data/db/mysql:/var/lib/mysql"
